# Generated by Django 4.2.6 on 2023-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='password',
        ),
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='卡密'),
        ),
    ]
